package com.aspose.cells;

import com.aspose.cells.b.c.a.za;

class zbvp
{
  private static final za a = new za(new String[] { "None", "TableStyleLight1", "TableStyleLight2", "TableStyleLight3", "TableStyleLight4", "TableStyleLight5", "TableStyleLight6", "TableStyleLight7", "TableStyleLight8", "TableStyleLight9", "TableStyleLight10", "TableStyleLight11", "TableStyleLight12", "TableStyleLight13", "TableStyleLight14", "TableStyleLight15", "TableStyleLight16", "TableStyleLight17", "TableStyleLight18", "TableStyleLight19", "TableStyleLight20", "TableStyleLight21", "TableStyleMedium1", "TableStyleMedium2", "TableStyleMedium3", "TableStyleMedium4", "TableStyleMedium5", "TableStyleMedium6", "TableStyleMedium7", "TableStyleMedium8", "TableStyleMedium9", "TableStyleMedium10", "TableStyleMedium11", "TableStyleMedium12", "TableStyleMedium13", "TableStyleMedium14", "TableStyleMedium15", "TableStyleMedium16", "TableStyleMedium17", "TableStyleMedium18", "TableStyleMedium19", "TableStyleMedium20", "TableStyleMedium21", "TableStyleMedium22", "TableStyleMedium23", "TableStyleMedium24", "TableStyleMedium25", "TableStyleMedium26", "TableStyleMedium27", "TableStyleMedium28", "TableStyleDark1", "TableStyleDark2", "TableStyleDark3", "TableStyleDark4", "TableStyleDark5", "TableStyleDark6", "TableStyleDark7", "TableStyleDark8", "TableStyleDark9", "TableStyleDark10", "TableStyleDark11", "InnerCustom" });
  
  static String a(int paramInt)
  {
    switch (paramInt)
    {
    case 0: 
      return "None";
    case 1: 
      return "TableStyleLight1";
    case 2: 
      return "TableStyleLight2";
    case 3: 
      return "TableStyleLight3";
    case 4: 
      return "TableStyleLight4";
    case 5: 
      return "TableStyleLight5";
    case 6: 
      return "TableStyleLight6";
    case 7: 
      return "TableStyleLight7";
    case 8: 
      return "TableStyleLight8";
    case 9: 
      return "TableStyleLight9";
    case 10: 
      return "TableStyleLight10";
    case 11: 
      return "TableStyleLight11";
    case 12: 
      return "TableStyleLight12";
    case 13: 
      return "TableStyleLight13";
    case 14: 
      return "TableStyleLight14";
    case 15: 
      return "TableStyleLight15";
    case 16: 
      return "TableStyleLight16";
    case 17: 
      return "TableStyleLight17";
    case 18: 
      return "TableStyleLight18";
    case 19: 
      return "TableStyleLight19";
    case 20: 
      return "TableStyleLight20";
    case 21: 
      return "TableStyleLight21";
    case 22: 
      return "TableStyleMedium1";
    case 23: 
      return "TableStyleMedium2";
    case 24: 
      return "TableStyleMedium3";
    case 25: 
      return "TableStyleMedium4";
    case 26: 
      return "TableStyleMedium5";
    case 27: 
      return "TableStyleMedium6";
    case 28: 
      return "TableStyleMedium7";
    case 29: 
      return "TableStyleMedium8";
    case 30: 
      return "TableStyleMedium9";
    case 31: 
      return "TableStyleMedium10";
    case 32: 
      return "TableStyleMedium11";
    case 33: 
      return "TableStyleMedium12";
    case 34: 
      return "TableStyleMedium13";
    case 35: 
      return "TableStyleMedium14";
    case 36: 
      return "TableStyleMedium15";
    case 37: 
      return "TableStyleMedium16";
    case 38: 
      return "TableStyleMedium17";
    case 39: 
      return "TableStyleMedium18";
    case 40: 
      return "TableStyleMedium19";
    case 41: 
      return "TableStyleMedium20";
    case 42: 
      return "TableStyleMedium21";
    case 43: 
      return "TableStyleMedium22";
    case 44: 
      return "TableStyleMedium23";
    case 45: 
      return "TableStyleMedium24";
    case 46: 
      return "TableStyleMedium25";
    case 47: 
      return "TableStyleMedium26";
    case 48: 
      return "TableStyleMedium27";
    case 49: 
      return "TableStyleMedium28";
    case 50: 
      return "TableStyleDark1";
    case 51: 
      return "TableStyleDark2";
    case 52: 
      return "TableStyleDark3";
    case 53: 
      return "TableStyleDark4";
    case 54: 
      return "TableStyleDark5";
    case 55: 
      return "TableStyleDark6";
    case 56: 
      return "TableStyleDark7";
    case 57: 
      return "TableStyleDark8";
    case 58: 
      return "TableStyleDark9";
    case 59: 
      return "TableStyleDark10";
    case 60: 
      return "TableStyleDark11";
    case 61: 
      return "InnerCustom";
    }
    return "InnerCustom";
  }
  
  static int a(String paramString)
  {
    switch (a.a(paramString))
    {
    case 0: 
      return 0;
    case 1: 
      return 1;
    case 2: 
      return 2;
    case 3: 
      return 3;
    case 4: 
      return 4;
    case 5: 
      return 5;
    case 6: 
      return 6;
    case 7: 
      return 7;
    case 8: 
      return 8;
    case 9: 
      return 9;
    case 10: 
      return 10;
    case 11: 
      return 11;
    case 12: 
      return 12;
    case 13: 
      return 13;
    case 14: 
      return 14;
    case 15: 
      return 15;
    case 16: 
      return 16;
    case 17: 
      return 17;
    case 18: 
      return 18;
    case 19: 
      return 19;
    case 20: 
      return 20;
    case 21: 
      return 21;
    case 22: 
      return 22;
    case 23: 
      return 23;
    case 24: 
      return 24;
    case 25: 
      return 25;
    case 26: 
      return 26;
    case 27: 
      return 27;
    case 28: 
      return 28;
    case 29: 
      return 29;
    case 30: 
      return 30;
    case 31: 
      return 31;
    case 32: 
      return 32;
    case 33: 
      return 33;
    case 34: 
      return 34;
    case 35: 
      return 35;
    case 36: 
      return 36;
    case 37: 
      return 37;
    case 38: 
      return 38;
    case 39: 
      return 39;
    case 40: 
      return 40;
    case 41: 
      return 41;
    case 42: 
      return 42;
    case 43: 
      return 43;
    case 44: 
      return 44;
    case 45: 
      return 45;
    case 46: 
      return 46;
    case 47: 
      return 47;
    case 48: 
      return 48;
    case 49: 
      return 49;
    case 50: 
      return 50;
    case 51: 
      return 51;
    case 52: 
      return 52;
    case 53: 
      return 53;
    case 54: 
      return 54;
    case 55: 
      return 55;
    case 56: 
      return 56;
    case 57: 
      return 57;
    case 58: 
      return 58;
    case 59: 
      return 59;
    case 60: 
      return 60;
    case 61: 
      return 61;
    }
    return 61;
  }
}


/* Location:              /media/peter/Data/gitworkspace/github/jxls_demo/libs/aspose-cells-17.10.jar!/com/aspose/cells/zbvp.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */